name: publish
on:
  push:
    tags: ["v*"]          # v1.0.0, v1.1.0‑rc1, etc.
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Publish to GitHub Packages
        run: ./mvnw -B deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # auto‑injected by GitHub
